### ISSUE TITLE
First class "type"

### ISSUE THREAD

**Issue by dataPulverizer** [BSVino/JaiPrimer#18]
One thing that was not mentioned in the primer was the treatment of "types" as first class programming elements. Is this still a thing? If so could I return a type from a function and could I have a dynamic array of types?

**Comment by BSVino** [comment]
I don't recall. He's not strong on type theory so I wouldn't be surprised if the answer is no.

**Comment by resistcorp** [comment]
[in this demo](https://www.youtube.com/watch?v=JoNkttD_MUs), Jon demoes run-time type info, so it is definitely possible.

**Comment by BSVino** [comment]
There you go.
