### ISSUE TITLE
There is too much "Blow" in the text

### ISSUE THREAD

**Issue by krux02** [BSVino/JaiPrimer#3]
I've read the text, and I really like the concept of the language, and also saw the videos. But I think that the authors name is mentioned too often. At the moment a `Strg+F` reveals a total of 23 times the use of "Blow".  I think mentioning his name in the introduction, and saying that he is the one who is responsible for the language and it's design decision should be enough, and then his reasons or thoughts for design decisions can be written as he would describe them, just without repeating "Blow" again.

**Comment by BSVino** [comment]
That's a good point. I don't have time at the moment to go through and do that though. If you make the changes and do me a pull request, I'll accept it.

**Comment by hasufell** [comment]
Now there is 7 Blows.

> Blow began work on Jai in late September 2014.

Pretty sure he was not the only one. And even if he was, how about "Work on Jai began in late September 2014"?

> Blow developed it with an eye towards video games, but in fact it’s a general purpose programming language that could be used for any task.

Use "It was developed with an eye..."

Also, you use "Jon Blow" twice. I find that inappropriate, you should use his complete name or just his surname.
