### ISSUE TITLE
Hope to communicate language design

### ISSUE THREAD

**Issue by kulics** [BSVino/JaiPrimer#30]
This language looks quite interesting.
Even more amazing is that the xylang I am currently developing is quite similar.
Maybe we have the same idea, which is a very lucky thing.

That's the language I wrote:
https://github.com/kulics/xylang

I really want to be able to exchange ideas on language design.
Is there any way I can get in touch?

**Comment by ErikWallstrom** [comment]
Maybe you want to join and post to [r/ProgrammingLanguages/](https://www.reddit.com/r/ProgrammingLanguages/)?  Pretty nice community full of language designers etc.

**Comment by hasufell** [comment]
Jai is a proprietary language with closed development and a single developer boasting how fast the compiler is on talks without having proper evidence. I wouldn't take it too seriously.

**Comment by kulics** [comment]
@ErikWallstrom Wow, this is a very good place, thank you for your advice.

**Comment by kulics** [comment]
@hasufell Of course, because I am also developing a programming language, Jai has a similar place with xy, so I am interested.

**Comment by Hurtak** [comment]
@kulics You can write directly to Jonathan Blow at language@thekla.com. He sometimes mentions this email in his youtube presentations about the language https://www.youtube.com/user/jblow888/videos.

**Comment by kulics** [comment]
@Hurtak Thank you for your information, I will try to contact.
