### ISSUE TITLE
>almost 2019 >semicolons

### ISSUE THREAD

**Issue by hugbubby** [BSVino/JaiPrimer#32]
into the trash it goes

**Comment by refi64** [comment]
And your point is?

The repo creator isn't the creator of Jai;  they're just collecting info about it into one place.

**Comment by hugbubby** [comment]
>And your point is?

my point is that the trash is where we put the languages that attempt to reinvent semicolons in 2019

thought that was pretty clear

**Comment by resistcorp** [comment]
>    thought that was pretty clear

It very much wasn't. Still isn't tbh.

**Comment by sigod** [comment]
Someone worked too much with Python and Go.

1. This is unofficial documentation.
2. The language isn't finished yet.
3. The syntax won't get any attention from the author until the language considered done.

Spamming over a hundred people with complaints about semicolons is just ridiculous. I apologize to everyone for having to read my message.

**Comment by yagodematos** [comment]
@hugbubby  this is not for webfags
